<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.nikola-velemir</groupId>
    
    <name>Poshtar Micronaut - Parent</name>
    
    <parent>
        <groupId>io.github.nikola-velemir</groupId>
        <artifactId>poshtar</artifactId>
        <version>1.1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>poshtar-micronaut</artifactId>
    <packaging>pom</packaging>

    <properties>
        <micronaut.version>4.10.9</micronaut.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.micronaut.platform</groupId>
                <artifactId>micronaut-platform</artifactId>
                <version>${micronaut.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <!-- Required to make Micronaut generate DI classes at compile time -->
                        <annotationProcessorPaths>
                            <path>
                                <groupId>io.micronaut</groupId>
                                <artifactId>micronaut-inject-java</artifactId>
                                <version>${micronaut.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>runtime</module>
        <module>processor</module>
        <module>integration-tests</module>
    </modules>
</project>