services:
  db:
    image: postgres:15
    container_name: poshtar-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poshtar_test
    ports:
      - "5433:5432"