spring.datasource.url=jdbc:postgresql://localhost:5433/poshtar_test
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=event.planner.team25@gmail.com
# Remove quotes, spaces, and comments from the value line
spring.mail.password=zbyflfzkqpprdjbf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true